import { createStitches } from '@stitches/react';
import {
	blue,
	blueDark,
	green,
	greenDark,
	mauve,
	mauveDark,
	purple,
	purpleDark,
	red,
	redDark,
} from '@radix-ui/colors';

export const {
	styled,
	css,
	globalCss,
	keyframes,
	getCssText,
	theme,
	createTheme,
	config,
} = createStitches({
	theme: {
		colors: {
			...blue,
			...green,
			...mauve,
			...purple,
			...red,

			hiContrast: '$mauve12',
			loContrast: 'white',
			canvas: 'hsl(0 0% 93%)',
			panel: 'white',
			transparentPanel: 'hsl(0 0% 0% / 97%)',
			shadowLight: 'hsl(206 22% 7% / 35%)',
			shadowDark: 'hsl(206 22% 7% / 20%)',
		},
		space: {
			1: '0.5rem',
			2: '1rem',
			3: '1.5rem',
			4: '2rem',
			5: '2.5rem',
			6: '3.5rem',
			7: '4.5rem',
			8: '6.5rem',
			9: '8rem',
		},
		sizes: {
			1: '0.5rem',
			2: '1rem',
			3: '1.5rem',
			4: '2rem',
			5: '2.5rem',
			6: '3.5rem',
			7: '4.5rem',
			8: '6.5rem',
			9: '8rem',
		},
		fonts: {
			body: "'Noto Serif', serif",
			display: "'Noto Sans Display', sans-serif",
			mono: "'Noto Sans Mono', monospace",
		},
		fontSizes: {
			1: '1.2rem',
			2: '1.3rem',
			3: '1.5rem',
			4: '1.7rem',
			5: '1.9rem',
			6: '2.1rem',
			7: '2.7rem',
			8: '3.5rem',
			9: '5.9rem',
		},
		fontWeights: {
			normal: 400,
			light: 300,
			bold: 700,
		},
		lineHeights: {
			m: 1.5,
			l: 2,
			s: 1,
		},
		radii: {
			1: '0.4rem',
			2: '0.6rem',
			3: '0.8rem',
			4: '1.2rem',
			round: '50%',
			pill: '9999px',
		},
		zIndices: {
			1: '100',
			2: '200',
			3: '300',
			4: '400',
			max: '999',
		},
	},
	media: {
		bp1: '(min-width: 520px)',
		bp2: '(min-width: 900px)',
		bp3: '(min-width: 1200px)',
		bp4: '(min-width: 1800px)',
		motion: '(prefers-reduced-motion)',
		hover: '(any-hover: hover)',
		dark: '(prefers-color-scheme: dark)',
		light: '(prefers-color-scheme: light)',
	},
});

export const darkTheme = createTheme({
	colors: {
		...blueDark,
		...greenDark,
		...mauveDark,
		...purpleDark,
		...redDark,

		hiContrast: '$mauve12',
		loContrast: '$mauve1',
		canvas: 'hsl(0 0% 15%)',
		panel: '$mauve3',
		transparentPanel: 'hsl(0 100% 100% / 97%)',
		shadowLight: 'hsl(206 22% 7% / 35%)',
		shadowDark: 'hsl(206 22% 7% / 20%)',
	},
});
