import { MigrationInterface, QueryRunner } from "typeorm";

export class init1659387968035 implements MigrationInterface {
    name = 'init1659387968035'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "session" ("expired_at" numeric NOT NULL, "id" text NOT NULL, "json" jsonb NOT NULL, "destroyed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bdf5fdcd0b49753475efec8397" ON "session" ("expired_at") `);
        await queryRunner.query(`CREATE TABLE "image_variant_types" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "cf_variant_name" text NOT NULL, "cf_variant_description" text NOT NULL, CONSTRAINT "PK_a629693f5978c3501052beb32ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."role" AS ENUM('owner', 'admin', 'user', 'guest')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" text NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "is_active" boolean NOT NULL, "role" "public"."role" NOT NULL DEFAULT 'guest', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "images" ("id" uuid NOT NULL, "file_name" text NOT NULL, "attribution" text NOT NULL, "alt_text" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "owner_id" integer, CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "image_variants" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "image_url" text NOT NULL, "variant_type" integer, "image_id" uuid, CONSTRAINT "PK_14d05d8745882c728dde0aa448c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_categories" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" text NOT NULL, "description" text, CONSTRAINT "PK_9c45c4e9fb6ebf296990e1d3972" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "slug" text NOT NULL, "published_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "author_id" integer, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_54ddf9075260407dcfdd724857" ON "posts" ("slug") `);
        await queryRunner.query(`CREATE TABLE "post_revisions" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" text NOT NULL, "text_json" jsonb, "text" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "post_id" integer, "authorId" integer, "hero_id" uuid, CONSTRAINT "PK_871219c3d5044d70ff7d59480b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_agency_types" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "type" text NOT NULL, CONSTRAINT "UQ_47fd355ee0198fe942d83b1615b" UNIQUE ("type"), CONSTRAINT "PK_2dc7735e66602d0ced71b63b646" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulse_point_city" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "city" text NOT NULL, "region" text NOT NULL, "country" text NOT NULL, CONSTRAINT "PK_a15dfc0cef8225a27d4609e9e0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_media" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "url" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "agency_id" integer, CONSTRAINT "PK_8afd669c6bdb6a76c4da082f249" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_agencies" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "pulsepoint_id" integer NOT NULL, "name" text NOT NULL, "short_name" text NOT NULL, "initials" text NOT NULL, "description" text NOT NULL, "agency_id" text NOT NULL, "city" text NOT NULL, "state" text NOT NULL, "country" text NOT NULL, "latitude" numeric NOT NULL, "longitude" numeric NOT NULL, "timezone" text NOT NULL, "psap" integer NOT NULL, "twitter_name" text, "facebook_name" text, "instagram_name" text, "linkedin_name" text, "youtube_url" text, "email" text, "website" text, "livestream" text, "cpr_only" boolean NOT NULL, "ogr_fid" integer NOT NULL, "boundary" polygon NOT NULL, "centroid" point NOT NULL, "image" text NOT NULL, "splashscreen" text NOT NULL, "has_unit_legend" boolean NOT NULL, "agency_type_id" integer, CONSTRAINT "UQ_e216d6e782de4f295221ef10b2b" UNIQUE ("pulsepoint_id"), CONSTRAINT "UQ_6afef241dead067e04882a2b404" UNIQUE ("agency_id"), CONSTRAINT "PK_fa6b096cc8e4cc8007a2c7ec86e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_incident_types" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" text NOT NULL, "description" text NOT NULL, CONSTRAINT "UQ_85cd06c6971b6a9abda1572a8bd" UNIQUE ("code"), CONSTRAINT "PK_e382ac94f02b8712bb31f2e476d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_incidents" ("id" bigint NOT NULL, "latitude" numeric NOT NULL, "longitude" numeric NOT NULL, "public" boolean NOT NULL, "call_received" TIMESTAMP WITH TIME ZONE NOT NULL, "call_closed" TIMESTAMP WITH TIME ZONE NOT NULL, "address_full" text NOT NULL, "address_medical" text NOT NULL, "address_truncated" boolean NOT NULL, "street_number" text, "common_place_name" text, "agency_id" integer, "incident_type" integer, CONSTRAINT "PK_d9a3447c5a8f3ac4716ddbacd6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pulsepoint_units" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "designator" text NOT NULL, "agency_id" integer, CONSTRAINT "PK_ad53664d565ed2918c872dbd23d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_revisions_categories_post_categories" ("postRevisionsId" integer NOT NULL, "postCategoriesId" integer NOT NULL, CONSTRAINT "PK_ba934a0295068686d7fbad1f787" PRIMARY KEY ("postRevisionsId", "postCategoriesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71a5b801268398fd2f313faefe" ON "post_revisions_categories_post_categories" ("postRevisionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98f2efd24da81d0aa3d3041d61" ON "post_revisions_categories_post_categories" ("postCategoriesId") `);
        await queryRunner.query(`CREATE TABLE "pulsepoint_agencies_cities_served_pulse_point_city" ("pulsepointAgenciesId" integer NOT NULL, "pulsePointCityId" integer NOT NULL, CONSTRAINT "PK_07dfa54ce4df1c0fe36713229a4" PRIMARY KEY ("pulsepointAgenciesId", "pulsePointCityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1fec704eed6ed58a26f405961" ON "pulsepoint_agencies_cities_served_pulse_point_city" ("pulsepointAgenciesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87d0b7d23c2325ca0c46588b1a" ON "pulsepoint_agencies_cities_served_pulse_point_city" ("pulsePointCityId") `);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "FK_89b9838539e754a5a5be3b5d265" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_variants" ADD CONSTRAINT "FK_452603516122d359de63fea5d59" FOREIGN KEY ("variant_type") REFERENCES "image_variant_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_variants" ADD CONSTRAINT "FK_eefcda781b381791a49de764256" FOREIGN KEY ("image_id") REFERENCES "images"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_312c63be865c81b922e39c2475e" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_revisions" ADD CONSTRAINT "FK_21715fae1f647ae1e4b0741346a" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_revisions" ADD CONSTRAINT "FK_e116cad825034bf4feca997cdb2" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_revisions" ADD CONSTRAINT "FK_c4515479751b4678641908ceefd" FOREIGN KEY ("hero_id") REFERENCES "images"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_media" ADD CONSTRAINT "FK_1221ae0e18e1f00d9a26016a224" FOREIGN KEY ("agency_id") REFERENCES "pulsepoint_agencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies" ADD CONSTRAINT "FK_0ed822a69026edda17daa8e2b13" FOREIGN KEY ("agency_type_id") REFERENCES "pulsepoint_agency_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_incidents" ADD CONSTRAINT "FK_04f7ca17815411249b54fefeeb0" FOREIGN KEY ("agency_id") REFERENCES "pulsepoint_agencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_incidents" ADD CONSTRAINT "FK_5f2fc528c2489f075fa0c689ca7" FOREIGN KEY ("incident_type") REFERENCES "pulsepoint_incident_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_units" ADD CONSTRAINT "FK_2ec5f5621339fc35318183503b9" FOREIGN KEY ("agency_id") REFERENCES "pulsepoint_agencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_revisions_categories_post_categories" ADD CONSTRAINT "FK_71a5b801268398fd2f313faefe0" FOREIGN KEY ("postRevisionsId") REFERENCES "post_revisions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_revisions_categories_post_categories" ADD CONSTRAINT "FK_98f2efd24da81d0aa3d3041d610" FOREIGN KEY ("postCategoriesId") REFERENCES "post_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies_cities_served_pulse_point_city" ADD CONSTRAINT "FK_f1fec704eed6ed58a26f4059619" FOREIGN KEY ("pulsepointAgenciesId") REFERENCES "pulsepoint_agencies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies_cities_served_pulse_point_city" ADD CONSTRAINT "FK_87d0b7d23c2325ca0c46588b1aa" FOREIGN KEY ("pulsePointCityId") REFERENCES "pulse_point_city"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies_cities_served_pulse_point_city" DROP CONSTRAINT "FK_87d0b7d23c2325ca0c46588b1aa"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies_cities_served_pulse_point_city" DROP CONSTRAINT "FK_f1fec704eed6ed58a26f4059619"`);
        await queryRunner.query(`ALTER TABLE "post_revisions_categories_post_categories" DROP CONSTRAINT "FK_98f2efd24da81d0aa3d3041d610"`);
        await queryRunner.query(`ALTER TABLE "post_revisions_categories_post_categories" DROP CONSTRAINT "FK_71a5b801268398fd2f313faefe0"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_units" DROP CONSTRAINT "FK_2ec5f5621339fc35318183503b9"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_incidents" DROP CONSTRAINT "FK_5f2fc528c2489f075fa0c689ca7"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_incidents" DROP CONSTRAINT "FK_04f7ca17815411249b54fefeeb0"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_agencies" DROP CONSTRAINT "FK_0ed822a69026edda17daa8e2b13"`);
        await queryRunner.query(`ALTER TABLE "pulsepoint_media" DROP CONSTRAINT "FK_1221ae0e18e1f00d9a26016a224"`);
        await queryRunner.query(`ALTER TABLE "post_revisions" DROP CONSTRAINT "FK_c4515479751b4678641908ceefd"`);
        await queryRunner.query(`ALTER TABLE "post_revisions" DROP CONSTRAINT "FK_e116cad825034bf4feca997cdb2"`);
        await queryRunner.query(`ALTER TABLE "post_revisions" DROP CONSTRAINT "FK_21715fae1f647ae1e4b0741346a"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_312c63be865c81b922e39c2475e"`);
        await queryRunner.query(`ALTER TABLE "image_variants" DROP CONSTRAINT "FK_eefcda781b381791a49de764256"`);
        await queryRunner.query(`ALTER TABLE "image_variants" DROP CONSTRAINT "FK_452603516122d359de63fea5d59"`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "FK_89b9838539e754a5a5be3b5d265"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87d0b7d23c2325ca0c46588b1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1fec704eed6ed58a26f405961"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_agencies_cities_served_pulse_point_city"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98f2efd24da81d0aa3d3041d61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71a5b801268398fd2f313faefe"`);
        await queryRunner.query(`DROP TABLE "post_revisions_categories_post_categories"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_units"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_incidents"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_incident_types"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_agencies"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_media"`);
        await queryRunner.query(`DROP TABLE "pulse_point_city"`);
        await queryRunner.query(`DROP TABLE "pulsepoint_agency_types"`);
        await queryRunner.query(`DROP TABLE "post_revisions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ddf9075260407dcfdd724857"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "post_categories"`);
        await queryRunner.query(`DROP TABLE "image_variants"`);
        await queryRunner.query(`DROP TABLE "images"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."role"`);
        await queryRunner.query(`DROP TABLE "image_variant_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdf5fdcd0b49753475efec8397"`);
        await queryRunner.query(`DROP TABLE "session"`);
    }

}
